Zenmo/Holon-webapp

- frontend/components/IntroductionVideo.js
- frontend/components/TextBlock.js
- frontend/components/WelcomePage.js
Adds the right text to the existing components
> Text content filling sprint1

- frontend/components/IntroductionVideo.js
- frontend/pages/index.js
- I've added id's to contentblocks that a buttons links to. 
- I've added these id's as links for the buttons.
> create ids and link buttons

- frontend/components/FeedbackBlock/SubscriptionForm.js
- frontend/components/WelcomePage.js
- frontend/content/privacy_page.md
- frontend/next.config.js
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/privacy.js
- frontend/tailwind.config.js
This branch deals with issue #25 
- Added a md file with the privacy agreement text
- This is rendered on the privacy page as html 
- The html is styled using the plug-in Tailwind Typography 
- The subscription form has a notification that by sending the information you agree to the privacy statement + link to the privacy statement.
> 25 privacy statement

- frontend/components/IntroductionVideo.js
- frontend/next.config.js
This issue solves #30 
- video no longer repeats itself; 
- holontool.nl/inbreng will route to holontool.nl/#feedback
> 30 inbreng route to feedback

- frontend/components/IntroductionVideo.js
- frontend/components/TextBlock.js
- frontend/components/WelcomePage.js
- frontend/pages/index.js
> textual updates from Auke

- frontend/components/Scenarios.js
- frontend/components/Scenarios/Scenarioslider.js
- frontend/components/Scenarios/Scenarioswitch.js
- frontend/styles/globals.css
- frontend/tailwind.config.js
> update slider styling

- frontend/components/CookieBar.js
- frontend/components/IntroductionVideo.js
- frontend/next.config.js
- frontend/pages/cookie-policy.js
- frontend/pages/index.js
- frontend/public/mdfiles/privacy_page.md
Closes #57 and #56 (see subtasks in issues)
> 57 survey release updates

- frontend/components/Scenarios/Scenarioswitch.js
> small fix in how the prop is named and passed

- frontend/components/Scenarios/Scenarioslider.js
- frontend/components/Scenarios/Scenarioswitch.js
The 'disabled' style of the scenario switches wasn't applied.
> 60 switches styling doesnt change when disabled

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- frontend/api/types.ts
- frontend/components/Header/Header.tsx
- frontend/components/Header/Navbar.tsx
- frontend/containers/BasePage/BasePage.tsx
- frontend/containers/StorylinePage/StorylinePage.tsx
- frontend/containers/WikiPage/WikiPage.test.tsx
- frontend/jest.config.js
- frontend/package-lock.json
- frontend/tsconfig.json
- src/main/mixins.py
- src/main/pages/base_serializer.py
- src/nextjs/api.py
When you add a page via Wagtail, you can tick the "Show in menu" box, under the SEO tab of the page you are creating. 
Only the second level - so the pages under Homepage - are shown. Submenu is out of scope.
Note: @pascalalferink if you see any styling changes who needs to fixed, be my guest. I only worked with Tailwind classes.
> 117 the main menu is automatically generated based on the cms

- frontend/components/Blocks/CardsBlock/Card.tsx
- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/CookieBar.tsx
- frontend/components/MediaContent/MediaContent.tsx
- frontend/components/Storyline/StorylineOverview/StorylineOverviewCard.tsx
- frontend/components/VersionOne/Header/Header.tsx
- frontend/components/VersionOne/Hero/Hero.tsx
Converted some Next Images to the default <img tags, because Azure (hosting) fixes the image sizes/resolution and if you use the Next Image tags on this it will result in errors.
This should fix the image bug on the accepatatie server
> 167 image naar img

- frontend/components/Blocks/CardsBlock/Card.tsx
> Image fix for card blocks

- frontend/containers/StorylinePage/StorylinePage.tsx
- src/holon/services/.cloudclient/config/config.yml
Adds the following blocks to the frontend of the Storyline page: 
- Title block
- Card block
- Hero block
> adds blocks to frontend storyline page

- frontend/api/holon.ts
> trying to fix the API url issue

- frontend/components/Blocks/ButtonsAndMediaBlock/ButtonsAndMediaBlock.tsx
Add the holonContentContainer class to the buttonsAndMediaBlock to set the max-width of the block equal to the page.
> Add class to buttons-media block

- .devcontainer/Dockerfile
- src/Dockerfile.prod
- src/requirements/base.txt
Wand (Pypi package) added.
Note @mattijsstam : Ik heb ImageMagick voor local development geinstalleerd in de .devcontainer/Dockerfile. Ik heb even niet scherp welke image er wordt gebuild voor productie. Als het dat bestand is, dan is het gefixed. Zo niet, moet dit worden toegevoegd aan het juiste bestand. Kan je me in dat geval vertellen waar ik dit moet doen?
> Installed Wand and Imagemagick (for local) to support animated GIFs

- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/KPIDashboard/KPIDashboard.test.tsx
- frontend/components/KPIDashboard/KPIDashboard.tsx
- frontend/components/KPIDashboard/KPIRadiobuttons.tsx
- frontend/components/KPIDashboard/exampleData.tsx
This PR addresses issue #283 : 
- by adding the dashboardid number to the name of each radio buttons group this issue should be solved.
> adds id to name of radio button group

- .github/workflows/build-push-images-azure.yml
- .github/workflows/django-code-quality.yml
- frontend/Dockerfile.prod
- frontend/api/wagtail.ts
- src/holon/services/.cloudclient/config/config.yml
Closes #284 
(warning: is still working with exposed API key and not with a nicely set API key from envs, no worries for now but a note for later)
> Change to private cloud

- .devcontainer/docker-entrypoint.sh
- src/holon/fixtures/main-casusfilter-fixture.json
Added fixtures for fill the data when you building the container on your dev env
> Add Casus Filters to fixtures for faster development

- src/holon/fixtures/mvp_datamodel.json
- src/holon/models/actor.py
- src/holon/models/asset.py
- src/holon/models/gridconnection.py
> Techdebt fixture

- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
The scrollintoview function needs to be fired async in Firefox
> Firefox fix for the tabs. Needs to fired async

- frontend/api/holon.ts
- frontend/components/Blocks/ContentBlocks.tsx
- frontend/components/Blocks/SectionBlock/CostBenefitModal/CostBenefitModal.tsx
- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/CostBenefit/CostBenefitChart.tsx
- frontend/components/UserProfile/UserProfile.tsx
- frontend/components/Wiki/Article.tsx
- frontend/containers/ChallengeModePage/ChallengeModePage.tsx
- frontend/containers/StorylinePage/StorylinePage.tsx
- frontend/containers/types.ts
- src/main/pages/challengemode_serializer.py
- src/main/pages/storyline_serializer.py
- src/nextjs/api.py
Note: de prettier zet nu ook volgordes van imports etc automatisch om. Wel nice! Maar zorgt nu wel voor veel changes die niet echt changes zijn.
> Fixed the graphcolors on the new main branch

- src/holon/services/cloudclient/client.py
- src/holon/views/holon.py
> Fix scenario dupes

- src/holon/models/rule_mapping.py
- src/holon/models/scenario.py
> Clone contracts too when cloning scenario

- src/holon/models/filter.py
> Fix relation filter clean function

- src/holon/models/rule_actions/rule_action_add_set.py
- src/holon/tests/test_rule_action_add.py
caused when queryset was empty
> fix rule action add set out of bounds bug

- frontend/components/KPIDashboard/KPIItems.tsx
> rounds numbers in KPIDashboard to one decimal

- src/holon/services/data.py
- src/holon/views/holon.py
> 550 Include scenario JSON in result on localhost and acceptatie

- src/holon/models/filter_subselector.py
> restore missing panel

- src/holon/models/filter.py
- src/holon/models/rule_actions/rule_action_change_attribute.py
- src/holon/models/scenario.py
- src/holon/models/scenario_rule.py
- src/holon/tests/test_rule_mapping.py
Implement Contract queryset on scenario rule so they can be edited.
> 611 fix contract queryset

- src/holon/models/scenario.py
- src/holon/tests/test_cleanup.py
- src/holon/tests/test_rule_action_change_attribute.py
- src/holon/urls.py
- src/holon/views/holon.py
Fixes issue where it tries to delete energyassets that are deleted because of an action.
Adds cleanup endpoint that easily removes cloned scenarios
Closes #585
> 585 scenarios not deleted

- src/holon/models/rule_actions/rule_action_add_set.py
> 620 Remove type exist check for rule action add

- src/holon/models/rule_actions/rule_action_add_set.py
- src/holon/tests/test_rule_action_add.py
> Ignore slider input when adding children

- src/holon/models/interactive_element.py
> add a better str representation for internal use

- frontend/components/InteractiveInputs/InteractiveInputPopover.tsx
- frontend/components/KPIDashboard/KPIItem.module.css
- frontend/components/KPIDashboard/KPIItem.tsx
Add a popover to each KPI with a link to the wiki.
> kpi wiki popovers

- src/holon/services/costs_table.py
> add rounding to table

- frontend/components/Blocks/SectionBlock/HolarchyTab/LegendModal.tsx
> fixes bug next Image in legend holarchy tab

- frontend/components/InteractiveInputs/InteractiveDropdown.tsx
> fixes dropdowns to show selected value

- src/pipit/settings/__init__.py
Throw an error when boolean enviroment value is unexpected.
> env: boolean improvement

- src/holon/services/costs_table.py
This saves about a minute of time in scenario Transitie Visie Warmte.
> costs: reduce queries for actor group

- .vscode/launch.json
- src/holon/cache/cache_runner/input_combinations.py
- src/holon/models/rule_mapping.py
- src/holon/models/scenario.py
- src/holon/models/util.py
- src/holon/serializers/interactive_element.py
- src/holon/services/clone_scenario.py
- src/holon/tests/test_cleanup.py
- src/holon/tests/test_scenario_clone.py
- src/holon/views/holon.py
implement various optimizations in and around Scenario.clone()
This reduces the number of database queries and total runtime of case Transitie Visie Warmte by almost 40%.
> clone: reduce queries

- src/pipit/settings/base.py
- src/pipit/settings/local.py
I had to change this to match the logic in Dockerfile.prod and use local pictures.
> settings: set media folder relative

- src/holon/views/holon.py
- src/pipit/sentry.py
Implement a cookie to disable caching.
> caching cookie

- src/holon/models/filter/filter.py
- src/holon/rule_engine/repositories/actor_repository.py
- src/holon/rule_engine/repositories/asset_repository.py
- src/holon/rule_engine/repositories/contract_repository.py
- src/holon/rule_engine/repositories/gridconnection_repository.py
- src/holon/rule_engine/repositories/gridnode_repository.py
- src/holon/rule_engine/repositories/policy_repository.py
- src/holon/rule_engine/repositories/repository_base.py
- src/holon/rule_engine/scenario_aggregate.py
- src/holon/tests/test_repository_filter_submodel.py
Implement filtering by model type in the repository
> new rule engine: filter by model type

- src/holon/models/filter/second_order_relation_attribute_filter.py
- src/holon/models/util.py
Expose _id fields in second order filter so you can have a third order filter as long as it's based on id.
> third order filter on id

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .vscode/launch.json
- src/holon/models/scenario_rule.py
- src/holon/rule_engine/repositories/repository_base.py
- src/holon/services/query_and_convert.py
Minimal effort, maximum effect
> Fixes depreciation costs and module inference

- src/holon/models/scenario_rule.py
- src/holon/rule_engine/repositories/repository_base.py
- src/holon/tests/aggregate/test_get_repository.py
- src/holon/tests/aggregate/test_merge.py
> Rename and improve repository join/merge and add tests

- scripts/acceptance-tail-webapp-logs.sh
- scripts/black-check.sh
- scripts/demote-all-users.sql
- src/holon/cache/cache_runner/cache_runner.py
Add scripts to
- check python style
- view logs of acceptance enviroment
- demote all users
- log output combinations of cache runner
Might be useful to someone other than me too.
> Utility scripts

- frontend/components/Wiki/Article.tsx
Change "inhoudsopgave" to "op deze pagina".
Part of https://github.com/ZEnMo/Holon-webapp/issues/816
> Wiki op deze pagina

- src/holon/services/costs_table.py
Remove undefined only once in case both group and subgroup are missing
> kosten-baten: fix remove undefined

- frontend/containers/ChallengeModePage/ChallengeModePage.tsx
- frontend/containers/SandboxPage/SandboxPage.tsx
De missende props in ChallengeMode en Sandbox page toegevoegd. 
Lost #838 op.
> Add wikilinks and pagetitle props to sandbox and challenge page

- frontend/components/InteractiveInputs/InteractiveInputPopover.tsx
- frontend/components/KPIDashboard/KPIItem.tsx
- frontend/components/KPIDashboard/KPIItems.tsx
Add a short, hardcoded description to the popout at the KPI.
> KPI: short description

- frontend/components/Blocks/CardsBlock/CardBlock.tsx
The cardblock had double vertical padding leading to somewhat excessive whitespace on the site. Removed this.
> cards: less vertical padding

- src/docker-entrypoint.prod.sh
Set number of workers depending on number of cores. To improve maximum throughput of the site.
> gunicorn: variable number of workers

- scripts/clean-container-registry.sh
Add script to manually remove container images which have no tag.
I have run this script today.
> Clean container registry

- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
> Sanbox popup text

- frontend/components/Blocks/SectionBlock/ScenarioModals/ScenarioModal.tsx
- frontend/components/KPIDashboard/KPIDashboard.tsx
The icon is still a floppy. Closes #879
> Rename save to share

- frontend/components/KPIDashboard/KPIItems.tsx
Format cost number on-demand depending on value height. Closes #882.
> Cost KPI number format

- frontend/components/Blocks/SectionBlock/CostBenefitModal/CostBenefitModal.tsx
- frontend/components/CostBenefit/CostBenefitChart.tsx
- frontend/components/CostBenefit/CostBenefitTable.tsx
Use betaalt or betalen and ontvangt or ontvangen depending on wether the subject seems plural.
Part of #886
> Cost benefit plural verbs

- src/holon/cache/holon_endpoint_cache/key_generator.py
- src/holon/models/rule_mapping.py
- src/holon/serializers/interactive_element.py
- src/holon/tests/aggregate/test_init.py
- src/holon/tests/aggregate/test_remove.py
- src/holon/tests/rule_actions/test_rule_action_add.py
- src/holon/tests/rule_actions/test_rule_action_add_multiple.py
- src/holon/tests/rule_actions/test_rule_action_attribute_noise.py
- src/holon/tests/rule_actions/test_rule_action_change_attribute.py
- src/holon/tests/rule_actions/test_rule_action_change_attribute_queried_value.py
- src/holon/tests/rule_actions/test_rule_action_remove.py
- src/holon/tests/rule_actions/test_rule_action_set_count.py
- src/holon/tests/test_etm_conversion.py
- src/holon/tests/test_filter.py
- src/holon/tests/test_filter_subselector.py
- src/holon/tests/test_rule_mapping.py
- src/holon/tests/test_rule_mapping_options.py
- src/holon/views/holon.py
- src/requirements/base.txt
> Speed up cache key calculation

- src/holon/models/rule_actions/rule_action_change_attribute.py
Before it was basically impossible to set a boolean to false because a non-empty string always is true.
> Rule engine can now set boolean false

- frontend/api/holon.ts
- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/KPIDashboard/KPIDashboard.tsx
- frontend/services/use-simulation.test.ts
- frontend/services/use-simulation.ts
- src/holon/views/holon.py
Display a message that the simulation is running when the cache check returned false.
> Display cache check

- frontend/api/wagtail.ts
- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/KPIDashboard/KPIDashboard.tsx
- frontend/components/KPIDashboard/KPIItems.tsx
- frontend/services/use-simulation.ts
- src/holon/services/data.py
- src/holon/views/holon.py
Display simulation error if any.
> Display errors

- frontend/components/Button/Button.tsx
- frontend/components/KPIDashboard/KPIDashboard.tsx
- frontend/components/KPIDashboard/KPIRadiobuttons.tsx
Also change the radiobuttons list from row layout to column layout so it fits better.
> Add upscaling info icons

- frontend/components/RawHtml/RawHtml.module.css
- frontend/styles/globals.css
Thicker link underlines. Terms are colored green.
> Link styling

- frontend/components/RawHtml/RawHtml.module.css
- frontend/public/imgs/wiki-pointer.svg
Replace default help cursor with a custom one with the text "wiki"
Part of #966
> Wiki cursor

- frontend/.eslintrc.json
- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/Button/Button.tsx
- frontend/components/Button/ShareButton.tsx
- frontend/components/KPIDashboard/CostBenefitButton.tsx
- frontend/components/KPIDashboard/HolarchyButton.tsx
- frontend/components/KPIDashboard/KPIDashboard.tsx
Move share button to top.
Move holarchy button to button.
Change floppy disk icon to share icon.
closes #964
> Redesign share button

- frontend/components/Blocks/SectionBlock/SectionBlock.tsx
- frontend/components/Blocks/SectionBlock/TwoColumn.tsx
- frontend/package-lock.json
- frontend/package.json
And remove @emotion/styled because it's no longer used.
> Always end a simulation section with a horizontal rule
