frontend/tailwind.config.js
- The `order-*` className is no longer needed since the welcome page was changed in 1fda047.
- Including the "sm" variant added *every* `*-sm` to the CSS. This resulted in large CSS and long compile times in development. I don't see anywhere that we dynamically create an `*-sm` className (any more), so it should be safe to remove.
**Before**
```
event - compiled client and server successfully in 19.2s (543 modules)
```
**After**
```
event - compiled client and server successfully in 732 ms (593 modules)
```
Closes #75
=> Remove Tailwind safelists

frontend/components/wiki/aside.jsx, frontend/components/wiki/breadcrumbs.jsx, frontend/pages/_wiki.jsx, frontend/pages/wiki/Sociaal/Gedrag/content.mdx, frontend/pages/wiki/This is markdown.mdx, frontend/pages/wiki/index.md, frontend/pages/wiki/this_is_markdown.mdx
Some alternatives to the current styling and layout of the wiki
1. Breadcrumb separated by "/" and on top of article
3. Only the `div` with the `prose` (aka the article) has scroll overflow. The rest is locked to match `100 vh`, with `8 vh` for the header.
3. Book icon with `span` and `href` in the header
=> alternative layout and styling

frontend/next.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/pages/_app.js, frontend/pages/_wiki.jsx, frontend/pages/wiki/index.mdx, frontend/styles/prism-ghcolors.css
This adds support for static pages in Next.js using MDX.
- Includes Prism for code highlighting, and Github-Flavored Markdown to parse tables.
- It turns out the default way to create a layout (header, footer, etc) means [having to import the layout into each Markdown file](https://nextjs.org/docs/advanced-features/using-mdx#layouts). This feels error-prone, so I added a `pages/_wiki.js` file which will act as a layout, and `pages/_app.js` will use it conditionally depending on whether the URL starts with /wiki.
- A default index wiki page is included. Additional pages can be added to the /wiki directory, or in sub-directories as desired.
This can either be merged as-is or used as a basis for creating the sidebar, breadcrumbs, etc.
Closes #71
=> Add static pages powered by MDX

frontend/cli/__Class/__Class.tsx, frontend/cli/__Pure/__Pure.tsx, frontend/components/Blocks/HeroBlock/HeroBlock.test.tsx, frontend/components/Blocks/HeroBlock/HeroBlock.tsx, frontend/components/Blocks/TitleBlock/TitleBlock.test.tsx, frontend/components/Blocks/TitleBlock/TitleBlock.tsx, frontend/components/MediaContent/MediaContent.tsx, frontend/components/RawHtml/RawHtml.tsx, frontend/components/VersionOne/Hero/Hero.tsx, frontend/components/WagtailUserbar/WagtailUserbar.tsx, frontend/containers/BasePage/BasePage.tsx, frontend/containers/BasePage/index.tsx, frontend/containers/HomePage/HomePage.tsx, frontend/containers/PasswordProtectedPage/PasswordProtectedPage.tsx, frontend/containers/PureHtmlPage/PureHtmlPage.tsx, frontend/containers/StaticPage/StaticPage.tsx, frontend/containers/StorylineOverviewPage/StorylineOverviewPage.tsx, frontend/containers/StorylinePage/StorylinePage.tsx, frontend/containers/WikiPage/WikiPage.test.tsx, frontend/containers/WikiPage/WikiPage.tsx, frontend/containers/types.ts
This PR is to partially complete #122. It removes the use of PropTypes throughout the components we got from Pipit. It also adds tests for some of these Pipit components, and others we've added recently.
I don't consider it to completely satisfy #122 since there are still many other recently-added components which are not tested, but I feel it's better to deal with this debt as we move forwards rather than in one huge pull request where it becomes increasingly difficult to handle the merge conflicts.
Feedback is very welcome.
*(I'm unsure who to assign this to for review; please reassign as you see fit).*
Closes #122.
=> Fixes TypeScript for Pipit components and adds some tests

src/main/pages/storylineoverview_serializer.py
Only fetch the children (that are always storylines) of a specific storylineoverviewpage instead of all storylines
=> Fetch only storyline childs instead of all

frontend/components/MediaContent/MediaContent.tsx
If no alt text was added to a video in a text-media block there was an error. This is fixed by only determining the alt text when an image is uploaded.
=> fixes bug alt text

.vscode/launch.json, src/main/pages/storyline.py, src/main/pages/storylineoverview_serializer.py
Error ontstond op de Storylinepage omdat deze Storylines inlaad, die (niet allemaal) een Thumbnail hadden. Daarop werd in de backend niet afgevangen dat dit eventueel leeg kon zijn.
=> Bugfix Storyline page. Fix when Thumbnail is empty

src/holon/wagtail_hooks.py
Adds GridConnections and Assets to the CMS, where content editors can edit the data.
=> Adding CMS pages for grid-connections and assets

package-lock.json, src/requirements/base.txt
Updates Wagtail from 4.0 to 4.1
Steps to install on local/server:
- pip install -r /src/requirements/base.txt
- python /src/manage.py migrate
=> Updated Wagtail version from 4.0 to 4.1

frontend/components/Wiki/Article.tsx, frontend/containers/WikiPage/WikiPage.tsx
This PR removes the extra Wiki header and changes the title of the page to HOLON Wiki (instead of 'Holon en de kunst van het loslaten').
=> removes wiki header and changes title page

.vscode/settings.json, src/holon/models/pepe.py, src/holon/services/etm_kpis.config.yml, src/holon/views.py
~~- [x] Should we synchronize `kpi_required_additional_hv_network_percentage` and `capacity_of_energy_flexibility_mv_batteries_electricity` such that they are both at the same net level?~~
Reverted the last point due to the fact that electric trucks hook in to the grid at the HV level (cc @marliekeverweij, right?)
=> Minor changes to the ETM upscaling module

frontend/components/Blocks/ParagraphBlock/ParagraphBlock.tsx, frontend/components/Card/Card.tsx
this pull request solves issue 235. 
- line-break is now word based. 
In addition I added a few lines to the paragraph block to ensure that the background color is outlined all the way to the left (it wasn't added to my commit in branch #179 which is already merged).
=> 235 button element should have a word based line break now it breaks halfway a word

frontend/.env.example, frontend/api/auth.ts, frontend/components/Header/Header.tsx, frontend/components/Header/Navbar.tsx, frontend/components/Login/LoginForm.tsx, frontend/components/Registration/RegistrationForm.tsx, frontend/components/Registration/SuccessModal.tsx, frontend/components/UserProfile/UpdatePassword.tsx, frontend/components/UserProfile/UserProfile.tsx
This pull request solves issue #340 . 
Inloggen: Als je bent ingelogd wordt je doorverwezen naar de homepage (en niet naar je profiel zoals nu);
Header: De username in de header moet een link zijn naar je profiel;
Header: Als je een voornaam hebt ingevuld staat deze in de header, anders je username (nu is dat altijd je username);
Profiel: als je bij ww wijzigen je oude wachtwoord niet goed hebt ingevuld krijg je hier een specifieke foutmelding van;
Profiel: foutmelding bij ww wijzigen liefst in rood (fout) of blauw (goed) en tussen onderste inputfield en button in;
api calls in een bestand zetten
=> 340 styling en opschonen inlog flow

frontend/components/Blocks/SectionBlock/ContentColumn.tsx, frontend/components/InteractiveInputs/InteractiveInputs.tsx, src/holon/models/rule_mapping.py, src/holon/tests/test_rule_mapping_options.py
Gebruik weer het option veld van InteractiveElementOption voor de api om aan te geven welke optie geselecteerd is. Hierdoor kan als de default van een interactive element wordt overschreven bij het instellen van een pagina (?) de option value gebruikt worden ipv het id. Id is lastig op te zoeken in het CMS.
=> Use option attribute value again for api

frontend/components/Blocks/HolarchyFeedbackImage/HolarchyFeedbackImage.tsx, frontend/components/Blocks/SectionBlock/ContentColumn.tsx, src/main/blocks/storyline_section.py
Een aantal fixes die bij een uitzonderelijke situatie - namelijk een niet geselecteerde interactive input, iets wat alleen mogelijk is via bijvoorbeeld een fixture en niet via het CMS - waarbij de applicatie nu niet meer crasht, maar er slechts minder fraai uit ziet (omdat er geen content is).
=> Fallbacks when there is no interactive input selected in the backend

src/holon/static/js/holon_chooser.js
Remove relation/foreign key options for model_attribute dropdown in the CMS. Foreign keys can't be used for filtering, as the ids are not stable.
Closes #600
=> 600 Remove relation options for model_attribute in the CMS

src/holon/models/filter.py, src/holon/models/util.py, src/holon/tests/test_filter.py
Add group and subgroup as valid options for Actor, because they have stable ids. Before they were excluded, because they're relations
=> Fix group and subgroup as valid actor attribute options

src/holon/models/filter.py, src/holon/tests/test_filter.py
Fixes clean function of RelationAttributeFilter when no subtype has been used
Closes #627
=> Fix clean function for relation attribute filter

.devcontainer/.env.example, README.md, docker-compose.yml, src/holon/services/data.py
A feature to help debug AnyLogic model results. This setting is used in the `/wt/api/nextjs/v2/holon/` endpoint to determine whether to send back the used scenario (through the serializer) or not. This should ideally not be set to true in production since it will impact performance.
```conf
RETURN_SCENARIO=True
```
One thing I'm unsure of is whether setting the Azure settings to this setting will be able to toggle this functionality without having to push a new container. If yes, then we can use this setting to develop with the content on main and later disable the functionality when we are happy with the outcomes.
=> add `RETURN_SCENARIO` env variables

src/holon/views/holon.py, src/pipit/sentry.py, src/pipit/settings/__init__.py, src/pipit/settings/local.py, src/pipit/settings/prod.py, src/pipit/settings/stage.py
Instead of removing the database spans from distributed tracing, merge spans which have the same parent. This way Sentry still gives some insight in the database usage.
Example output:
=> sentry: consolidate database spans

src/holon/models/rule_mapping.py, src/holon/services/cloudclient/client.py, src/holon/services/query_and_convert.py, src/holon/views/holon.py
Log input and output of ETM costs and upscaling.
Example logging of cost:
Example logging of scaling:
=> sentry: log ETM variables

src/pipit/sentry.py, src/pipit/test_sentry.py
On Azure sentry spans aren't consolidated because it runs on UTC timezone and Python <3.11 has a shortcoming parsing this format.
=> sentry: fix datetime parse error

src/holon/models/rule_actions/rule_action_add_set.py, src/holon/models/rule_actions/rule_action_balance_group.py, src/holon/templates/modelconfig.html, src/holon/views/holon.py, src/pipit/settings/base.py, src/pipit/urls.py, src/requirements/base.txt
- is_rule_action_template wordt bij toevoegen bij bijv. RuleActionAdd op false gezet, zodat deze niet in de dropdowns komt in het CMS -> Geen oplopende laaddtijden
- Caching /modelconfig had geen zin omdat dit maar enkele ms duurde
- Modelconfig wordt autmatisch leesbaar gedocumenteerd in http://localhost:8000/wt/cms/modelconfig/schema
- Api's worden automatisch gedocumenteerd in http://localhost:8000/wt/api/schema/swagger
Closes #699 
Bij goedkeuring zal ik het in de wiki zetten :)
=> 699 dropdown performance improvements

frontend/components/Blocks/ContentBlocks.tsx, frontend/components/Blocks/SectionBlock/ContentColumn.tsx, src/holon/models/interactive_element.py, src/main/blocks/storyline_section.py
This PR closes #701 
Instead of added the target values at the end of the array with interactive inputs it now places them at the beginning (while keeping the order in which they are added to the page). 
It also fixes a small bug in which multi-select elements where being send along with target values as default values in the section they were placed in (instead of only in their underlying sections). 
It also hides the option to give an interactive element snippet a default value. This option is not used by the modelers and it gives undesired behaviour when adding an element with a target value.
=> changes order of interactive elements with target values

src/pipit/sentry.py
Require the user to set a cookie or query parameter to enable Sentry tracing. This is to reduce the bill for Sentry. Errors will still be sent always.
=> sentry: only trace on-demand

src/holon/models/filter.py, src/holon/models/rule_actions/rule_action_change_attribute.py, src/holon/models/scenario_rule.py, src/holon/models/util.py, src/holon/tests/test_filter.py, src/holon/tests/test_rule_action_change_attribute.py, src/holon/views/holon.py
De PR zorgt ervoor dat group en subgroup van een Actor veranderd kunnen worden. De id's van deze relaties blijven namelijk gelijk. Door '_id' achter het model attribuut te zetten, kan er met static value of interactief element een ander id worden meegegeven.
Voor filteren hoeft er voor django niet per se '_id' achter te staan, dus dat is zo gelaten om alles zo simpel mogelijk te houden
Closes #711
=> Add group_id and subgroup_id options for CMS

.devcontainer/docker-compose.yml, .github/workflows/django-code-quality.yml, db/Dockerfile, docker-compose.yml, docker/Dockerfile, frontend/Dockerfile, frontend/prod.Dockerfile
Set a specific version for nginx, node, postgres and python so that
it doesn't break due to a stale image version in the local cache or
the release of a new (major) version.
Also align production and development versions.
=> docker: align image versions

src/holon/rule_engine/repositories/repository_base.py, src/holon/tests/repository/test_repository_init.py
Set original_id when creating a repository. This is to main compatibility with scenario rules that  use this attribute since the the id's were not stable
=> 735 set original

.github/workflows/build-push-images-azure.yml
Enable caching for docker. When the cache is used it reduces the build time from 10 to 1 minute. This reduces the time to deploy.
=> cache docker layers

src/holon/static/js/holon_chooser.js
Enable filtering and change relations by id with interactive elements. These options were removed with jQuery.
This is now only allowed for actor group and subgroup due to existing backend validation.
The ideal situation would be to make the front-end options dependent on the backend validation so it is always in sync. (single source of truth)
=> Interactive element: allow relations

frontend/components/Blocks/SectionBlock/CostBenefitModal/CostBenefitModal.tsx, frontend/components/Blocks/SectionBlock/HolarchyTab/HolarchyTab.tsx, frontend/components/Blocks/SectionBlock/SectionBlock.tsx
This issue addresses #792. 
This had to do with the new height of the header and not with the sandbox page. I've also adjusted the distance to the header in the section menu bar, the holarchy tab and the kostenbaten view. Next to that I've also adjusted the z-index of a few items so they overlap correctly and the shadow box of the section menu bar is now only showing below (relevant for big screens).
=> adjusts styling to new height header

src/holon/services/costs_table.py, src/holon/tests/rule_actions/test_rule_action_change_attribute.py, src/holon/tests/test_costs_table.py, src/holon/views/holon.py
Use scenario aggregate in cost table. This solves the issue where newly added actors can't be found, since the rule engine works in memory now.
=> Use scenario aggregate in cost table

src/holon/rule_engine/repositories/actor_group_repository.py, src/holon/rule_engine/repositories/actor_sub_group_repository.py, src/holon/rule_engine/scenario_aggregate.py
Load all actor groups and subgroups for usage by the rule engine. This fixes casus transitievisie warmte.
=> rule engine: load all actor groups

src/holon/models/rule_actions/rule_action_change_attribute.py, src/holon/tests/rule_actions/test_rule_action_change_attribute.py
When changing a relation through change attribute, make sure the id is an integer to prevent errors later on.
=> rule action change attribute: set int id

src/holon/services/cloudclient/client.py, src/holon/services/query_and_convert.py, src/pipit/sentry.py
Log anylogic input and output to Sentry if tracing is enabled. This allows to debug and validate the scenarios.
Sample output: https://zenmo.sentry.io/performance/holon:6922a42c31d64a8a81d7655c88e4d1b6/?environment=erik&project=4505045759361024&query=http.method%3APOST&referrer=performance-transaction-summary&statsPeriod=1h&transaction=%2Fwt%2Fapi%2Fnextjs%2Fv2%2Fholon%2F&unselectedSeries=p100%28%29
(check the metadata of CloudClient.run)
=> Log anylogic output

src/holon/rule_engine/repositories/repository_base.py, src/holon/tests/aggregate/test_add.py
By updating the pk field when adding instances to a repository, objects are not wrongly considered equal anymore.
Before when adding multiple template instances to a repository all were considered equal, because only the id field was updated and Django. This caused the set() function used for merging repositories to remove too much instances.
Kudos to @thesethtruth for debugging :)
Closes #820
=> Update pk when adding instances to a repository

src/holon/models/interactive_element.py, src/holon/tests/test_cache.py
Fix bug where the cache runner would only produce whole numbers (integers) but the web front-end also produces fractional values. This prevented pre-generation some cache combinations.
=> cache runner: fractional numbers

src/holon/cache/cache_runner/cache_runner.py
The number of cache workers was accidentally hardcoded to 14.
=> cache workers: configurable number

frontend/components/CostBenefit/CostBenefitTable.tsx
Add thousand separators to cost-benefit tables. Also round numbers to 4 significant digits. Less significant digits are displayed as 0.
Closes #884
=> Table thousand separators

frontend/components/Blocks/SectionBlock/CostBenefitModal/CostBenefitModal.tsx, frontend/components/CostBenefit/CostBenefitChart.tsx, frontend/components/CostBenefit/CostBenefitTable.tsx
Move the label "cost-benefit" so it no longer overlaps with the number scale of the Y axis.
Fixes https://github.com/ZEnMo/Holon-webapp/issues/876
=> Cost-benefit graph: move label
